on:
  release:
    types: [published]
name: Builds and pushes tagged image to ECR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        run: docker build -t gh-runner:${{github.event.release.tag_name}} -t latest .
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_ACCESS_ID }}
          secret-access-key: ${{ secrets.ECR_ACCESS_KEY }}
          region: us-east-1
          image: gh-runner:${{github.event.release.tag_name}}