on:
  push:
    tags:
      - 'v*'
name: Builds and pushes tagged image to ECR
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create GitHub release
        run: docker build -t gh-runner:${{ steps.get_version.outputs.VERSION }} -t latest .

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_ACCESS_ID }}
          secret-access-key: ${{ secrets.ECR_ACCESS_KEY }}
          region: us-east-1
          image: gh-runner:${{ steps.get_version.outputs.VERSION }}    
