name: Builds and pushes an image to DockerHub

on:
  push:
    branches: [ master ]

jobs:
  build_push_docker_hub:
    name: Push image Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Buildx to build image
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            mamorufoundation/gh-runner:latest
            mamorufoundation/gh-runner:${{ github.sha }}
