
# https://github.com/actions/checkout/issues/95
# https://github.community/t/github-action-action-in-private-repository/16063/28

name: Check GH Runner
on: [workflow_dispatch]

jobs:
  pre-job-test:
    runs-on: ubuntu-latest
    steps:
    - name: Provide a self hosted to execute this job
      uses: PasseiDireto/gh-runner-task-action@main
      with:
        github_pat: ${{ secrets.PD_BOT_GITHUB_ACCESS_TOKEN }}
        task_definition: 'gh-runner'
        cluster: 'gh-runner'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CDK_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_SECRET_KEY }}
        AWS_DEFAULT_REGION:  ${{secrets.AWS_DEFAULT_REGION}}
  runs-dummy-action:
    runs-on: self-hosted
    container:
      image: python:3.9-slim
    needs: pre-job-test
    steps:
    - uses: actions/checkout@v2
    - run: python --version
